/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
 
import type { Item, Table } from 'airtable-ts'

export interface DocumentList extends Item {
  id: string
  name: string | null // Original field: "Name"
  politician: string | null // Original field: "Politician"
  document: string[] // Original field: "Document"
  uRL: string | null // Original field: "URL"
  country: string | null // Original field: "Country"
  region: string | null // Original field: "Region"
  language: string | null // Original field: "Language"
  type: string | null // Original field: "Type"
  yearFrom: number | null // Original field: "Year From"
  yearTo: number | null // Original field: "Year To"
  processed: boolean // Original field: "Processed"
}

export const documentListTable: Table<DocumentList> = {
  name: 'DocumentList',
  baseId: 'appV6P50gXopHlZDz',
  tableId: 'tblB6GTngv6JuqjYd',
  mappings: {
    name: 'fldfRWeGVokan0kdW', // Original field: "Name"
    politician: 'fldrQwYXWwIAjJW3H', // Original field: "Politician"
    document: 'fldNR8OpFNTkDiChZ', // Original field: "Document"
    uRL: 'fldVgpUO0sJsaAkNy', // Original field: "URL"
    country: 'flduzcOaF6S89zzSg', // Original field: "Country"
    region: 'fldI6MT4hR5IdNcBu', // Original field: "Region"
    language: 'fldoMWeclFGJ1niEu', // Original field: "Language"
    type: 'fldrTWwAINZuSkgf2', // Original field: "Type"
    yearFrom: 'fldwLrR1TokUdTBjq', // Original field: "Year From"
    yearTo: 'fldihbn4zxphflXGE', // Original field: "Year To"
    processed: 'fldtQBIgzqW6hcdob', // Original field: "Processed"
  },
  schema: {
    name: 'string | null',
    politician: 'string | null',
    document: 'string[]',
    uRL: 'string | null',
    country: 'string | null',
    region: 'string | null',
    language: 'string | null',
    type: 'string | null',
    yearFrom: 'number | null',
    yearTo: 'number | null',
    processed: 'boolean',
  },
}
