/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from "airtable-ts";

export interface Countrie extends Item {
  id: string;
  name: string | null; // Original field: "Name"
  country: string | null; // Original field: "Country"
  language: string | null; // Original field: "Language"
  politicalEntities: string[]; // Original field: "Political Entities"
}

export const countriesTable: Table<Countrie> = {
  name: "Countries",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tbl1UynrhPUg2TUwM",
  mappings: {
    name: "fld9B0heQiLDAoybE", // Original field: "Name"
    country: "fld2hAt2UYxtu6D3S", // Original field: "Country"
    language: "fldE7W8AuDTFJfLKA", // Original field: "Language"
    politicalEntities: "fldv0fHpjVt76Dzus", // Original field: "Political Entities"
  },
  schema: {
    name: "string | null",
    country: "string | null",
    language: "string | null",
    politicalEntities: "string[]",
  },
};

export interface PoliticalEntitie extends Item {
  id: string;
  name: string | null; // Original field: "Name"
  country: string[]; // Original field: "Country"
  region: string | null; // Original field: "Region"
  title: string | null; // Original field: "Title"
  image: string[]; // Original field: "Image"
  periodFrom: number | null; // Original field: "Period From"
  periodTo: number | null; // Original field: "Period To"
  documents: string[]; // Original field: "Documents"
  fromFieldCountries: string | null; // Original field: "From field: Countries"
}

export const PoliticalEntitiestable: Table<PoliticalEntitie> = {
  name: "Political Entities",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tblcG5EsXTJQR9hjG",
  mappings: {
    name: "fld1FWqna31julgPx", // Original field: "Name"
    country: "fldPni13E24x2amsg", // Original field: "Country"
    region: "fldKAIDG7xcs5qSoq", // Original field: "Region"
    title: "fldiLMNUttR9KOmMK", // Original field: "Title"
    image: "fldMoqDln4BQORsJU", // Original field: "Image"
    periodFrom: "fldtQ4jnZMxIcZwME", // Original field: "Period From"
    periodTo: "fldVycONaMHHgSejz", // Original field: "Period To"
    documents: "fldArnGY008ctfl4z", // Original field: "Documents"
    fromFieldCountries: "fldERuoEvwI0lYESE", // Original field: "From field: Countries"
  },
  schema: {
    name: "string | null",
    country: "string[]",
    region: "string | null",
    title: "string | null",
    image: "string[]",
    periodFrom: "number | null",
    periodTo: "number | null",
    documents: "string[]",
    fromFieldCountries: "string | null",
  },
};

export interface Document extends Item {
  id: string;
  name: string | null; // Original field: "Name"
  politicalEntity: string[]; // Original field: "Political Entity"
  documents: string[]; // Original field: "Documents"
  uRL: string | null; // Original field: "URL"
  language: string | null; // Original field: "Language"
  type: string | null; // Original field: "Type"
  processed: boolean; // Original field: "Processed"
}

export const documentsTable: Table<Document> = {
  name: "Documents",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tblr2Fgcp72DZRIYA",
  mappings: {
    name: "fld9QnLqtlxNG01y7", // Original field: "Name"
    politicalEntity: "fld2EzQonJMdbxKPn", // Original field: "Political Entity"
    documents: "fldh5oOdQPVvWHcD0", // Original field: "Documents"
    uRL: "fldZt8syqIsaoK4Po", // Original field: "URL"
    language: "fldRc94TevhAyp7rI", // Original field: "Language"
    type: "fldeUJnxUWx5vxY89", // Original field: "Type"
    processed: "fld0F473Wlvj5V28m", // Original field: "Processed"
  },
  schema: {
    name: "string | null",
    politicalEntity: "string[]",
    documents: "string[]",
    uRL: "string | null",
    language: "string | null",
    type: "string | null",
    processed: "boolean",
  },
};
