/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from "airtable-ts";

export interface Countrie extends Item {
  id: string;
  name: string | null; // Original field: "Name"
  country: string | null; // Original field: "Country"
  language: string | null; // Original field: "Language"
  duplicateError: boolean; // Original field: "⚠️ DUPLICATE ERROR"
  publishThisCountry: boolean; // Original field: "Publish this Country"
  politicalEntities: string[]; // Original field: "Political Entities"
  documents: string[]; // Original field: "Documents"
  duplicateCheck: string | null; // Original field: "Duplicate Check"
}

export const countriesTable: Table<Countrie> = {
  name: "Countries",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tbl1UynrhPUg2TUwM",
  mappings: {
    name: "fld9B0heQiLDAoybE", // Original field: "Name"
    country: "fld2hAt2UYxtu6D3S", // Original field: "Country"
    language: "fldE7W8AuDTFJfLKA", // Original field: "Language"
    duplicateError: "fldktFZgJ2oxqcnYX", // Original field: "⚠️ DUPLICATE ERROR"
    publishThisCountry: "fldCjdVAGmXl40u9g", // Original field: "Publish this Country"
    politicalEntities: "fldv0fHpjVt76Dzus", // Original field: "Political Entities"
    documents: "fldMzHmm8uHk9qgpd", // Original field: "Documents"
    duplicateCheck: "fldhRnIx7TOSPeGPR", // Original field: "Duplicate Check"
  },
  schema: {
    name: "string | null",
    country: "string | null",
    language: "string | null",
    duplicateError: "boolean",
    publishThisCountry: "boolean",
    politicalEntities: "string[]",
    documents: "string[]",
    duplicateCheck: "string | null",
  },
};

export interface PoliticalEntitie extends Item {
  id: string;
  politicalEntityName: string | null; // Original field: "Political Entity Name"
  country: string[]; // Original field: "Country"
  region: string | null; // Original field: "Region"
  title: string | null; // Original field: "Title"
  image: string[]; // Original field: "Image"
  periodFrom: number | null; // Original field: "Period From"
  periodTo: number | null; // Original field: "Period To"
  status: string | null; // Original field: "Status"
  documents: string[]; // Original field: "Documents"
  fromFieldCountries: string | null; // Original field: "From field: Countries"
  documents2: string[]; // Original field: "Documents 2"
  documents3: string[]; // Original field: "Documents 3"
  documents4: string[]; // Original field: "Documents 4"
  documents5: string[]; // Original field: "Documents 5"
}

export const PoliticalEntitiestable: Table<PoliticalEntitie> = {
  name: "Political Entities",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tblcG5EsXTJQR9hjG",
  mappings: {
    politicalEntityName: "fld1FWqna31julgPx", // Original field: "Political Entity Name"
    country: "fldPni13E24x2amsg", // Original field: "Country"
    region: "fldKAIDG7xcs5qSoq", // Original field: "Region"
    title: "fldiLMNUttR9KOmMK", // Original field: "Title"
    image: "fldMoqDln4BQORsJU", // Original field: "Image"
    periodFrom: "fldtQ4jnZMxIcZwME", // Original field: "Period From"
    periodTo: "fldVycONaMHHgSejz", // Original field: "Period To"
    status: "flduSYKzI0EpDwTe9", // Original field: "Status"
    documents: "fldArnGY008ctfl4z", // Original field: "Documents"
    fromFieldCountries: "fldERuoEvwI0lYESE", // Original field: "From field: Countries"
    documents2: "fldiihAK54nKrE5hb", // Original field: "Documents 2"
    documents3: "fld3uaeDsE602c8h6", // Original field: "Documents 3"
    documents4: "fldhc4Jq4PvD9JFW1", // Original field: "Documents 4"
    documents5: "fldzMVkyVNmeVfhjQ", // Original field: "Documents 5"
  },
  schema: {
    politicalEntityName: "string | null",
    country: "string[]",
    region: "string | null",
    title: "string | null",
    image: "string[]",
    periodFrom: "number | null",
    periodTo: "number | null",
    status: "string | null",
    documents: "string[]",
    fromFieldCountries: "string | null",
    documents2: "string[]",
    documents3: "string[]",
    documents4: "string[]",
    documents5: "string[]",
  },
};

export interface Document extends Item {
  id: string;
  documentName: string | null; // Original field: "Document Name"
  politicalEntity: string[]; // Original field: "Political Entity"
  documents: string[]; // Original field: "Documents"
  docSourceUrl: string | null; // Original field: "Doc Source URL"
  language: string | null; // Original field: "Language"
  type: string | null; // Original field: "Type"
  processed: boolean; // Original field: "Processed"
  status: string | null; // Original field: "Status"
  statusDate: number | null; // Original field: "Status date"
  selectCountry: string[]; // Original field: "Select Country"
  nameFromCountries: string | null; // Original field: "Name (from Countries)"
  countryFromCountries: string | null; // Original field: "Country (from Countries)"
  politicalEntitiesFromCountries: string[] | null; // Original field: "Political Entities (from Countries)"
  addAPoliticalEntity: string[]; // Original field: "Add a Political entity"
  politicalEntityNameFromAddAPoliticalEntity: string | null; // Original field: "Political Entity Name (from Add a Political entity)"
  countryFromAddAPoliticalEntity: string[] | null; // Original field: "Country (from Add a Political entity)"
  regionFromAddAPoliticalEntity: string | null; // Original field: "Region (from Add a Political entity)"
  titleFromAddAPoliticalEntity: string | null; // Original field: "Title (from Add a Political entity)"
  imageFromAddAPoliticalEntity: string[] | null; // Original field: "Image (from Add a Political entity)"
  periodFromFromAddAPoliticalEntity: number | null; // Original field: "Period From (from Add a Political entity)"
  periodToFromAddAPoliticalEntity: number | null; // Original field: "Period To (from Add a Political entity)"
  documentsFromAddAPoliticalEntity: string[] | null; // Original field: "Documents (from Add a Political entity)"
  fromFieldCountriesFromAddAPoliticalEntity: string | null; // Original field: "From field: Countries (from Add a Political entity)"
  politicalEntities: string[]; // Original field: "Political Entities"
  politicalEntityNameFromPoliticalEntities: string | null; // Original field: "Political Entity Name (from Political Entities)"
  countryFromPoliticalEntities: string[] | null; // Original field: "Country (from Political Entities)"
  regionFromPoliticalEntities: string | null; // Original field: "Region (from Political Entities)"
  titleFromPoliticalEntities: string | null; // Original field: "Title (from Political Entities)"
  imageFromPoliticalEntities: string[] | null; // Original field: "Image (from Political Entities)"
  periodFromFromPoliticalEntities: number | null; // Original field: "Period From (from Political Entities)"
  periodToFromPoliticalEntities: number | null; // Original field: "Period To (from Political Entities)"
  politicalEntities2: string[]; // Original field: "Political Entities 2"
  regionFromPoliticalEntities2: string | null; // Original field: "Region (from Political Entities 2)"
  titleFromPoliticalEntities2: string | null; // Original field: "Title (from Political Entities 2)"
  imageFromPoliticalEntities2: string[] | null; // Original field: "Image (from Political Entities 2)"
  periodFromFromPoliticalEntities2: number | null; // Original field: "Period From (from Political Entities 2)"
  periodToFromPoliticalEntities2: number | null; // Original field: "Period To (from Political Entities 2)"
  politicalEntities3: string[]; // Original field: "Political Entities 3"
  titleFromPoliticalEntities3: string | null; // Original field: "Title (from Political Entities 3)"
}

export const documentsTable: Table<Document> = {
  name: "Documents",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tblr2Fgcp72DZRIYA",
  mappings: {
    documentName: "fld9QnLqtlxNG01y7", // Original field: "Document Name"
    politicalEntity: "fld2EzQonJMdbxKPn", // Original field: "Political Entity"
    documents: "fldh5oOdQPVvWHcD0", // Original field: "Documents"
    docSourceUrl: "fldZt8syqIsaoK4Po", // Original field: "Doc Source URL"
    language: "fldRc94TevhAyp7rI", // Original field: "Language"
    type: "fldeUJnxUWx5vxY89", // Original field: "Type"
    processed: "fld0F473Wlvj5V28m", // Original field: "Processed"
    status: "fldGo9feO6HiBQ1Zj", // Original field: "Status"
    statusDate: "fldbnGiaEJFL3yALB", // Original field: "Status date"
    selectCountry: "fldwcjBq1FRS8JgdA", // Original field: "Select Country"
    nameFromCountries: "fldxx7Lw0ijjkSEvf", // Original field: "Name (from Countries)"
    countryFromCountries: "fldwEnkdd3PVyP1ov", // Original field: "Country (from Countries)"
    politicalEntitiesFromCountries: "fldcdBbfDWzVYeFSX", // Original field: "Political Entities (from Countries)"
    addAPoliticalEntity: "fld4bGm3K2l0IXZrj", // Original field: "Add a Political entity"
    politicalEntityNameFromAddAPoliticalEntity: "fldEz4ZPuAkXk4eee", // Original field: "Political Entity Name (from Add a Political entity)"
    countryFromAddAPoliticalEntity: "fld1dps3uUMtlv9VF", // Original field: "Country (from Add a Political entity)"
    regionFromAddAPoliticalEntity: "fldA4ApnIoOh5mGUs", // Original field: "Region (from Add a Political entity)"
    titleFromAddAPoliticalEntity: "fldIro5jYN8youxDP", // Original field: "Title (from Add a Political entity)"
    imageFromAddAPoliticalEntity: "fldm5QUBYCiqA61MW", // Original field: "Image (from Add a Political entity)"
    periodFromFromAddAPoliticalEntity: "fldjt9XXr35lk6bGg", // Original field: "Period From (from Add a Political entity)"
    periodToFromAddAPoliticalEntity: "fldYrwJhq8anVoOEB", // Original field: "Period To (from Add a Political entity)"
    documentsFromAddAPoliticalEntity: "fld55ZHhUjSCi4kB3", // Original field: "Documents (from Add a Political entity)"
    fromFieldCountriesFromAddAPoliticalEntity: "fldiUj2agIE1WE3Co", // Original field: "From field: Countries (from Add a Political entity)"
    politicalEntities: "fldpSJbzE7KYLftXS", // Original field: "Political Entities"
    politicalEntityNameFromPoliticalEntities: "fldJP5bg7x1IUHfsJ", // Original field: "Political Entity Name (from Political Entities)"
    countryFromPoliticalEntities: "fld0fl1pnWQs2NeYn", // Original field: "Country (from Political Entities)"
    regionFromPoliticalEntities: "fld9doP0eRN1TgBuQ", // Original field: "Region (from Political Entities)"
    titleFromPoliticalEntities: "fldRcStqb8twvbTiY", // Original field: "Title (from Political Entities)"
    imageFromPoliticalEntities: "fldjEdr0SdHu6oHgk", // Original field: "Image (from Political Entities)"
    periodFromFromPoliticalEntities: "fldeRB3UGiB0nDyrC", // Original field: "Period From (from Political Entities)"
    periodToFromPoliticalEntities: "fldTfkFNjMyHLPDMI", // Original field: "Period To (from Political Entities)"
    politicalEntities2: "fldXQuwTQ1CiTJVXl", // Original field: "Political Entities 2"
    regionFromPoliticalEntities2: "fldMaqvqLsKYlufG1", // Original field: "Region (from Political Entities 2)"
    titleFromPoliticalEntities2: "fldal15Ku5fd8mc5t", // Original field: "Title (from Political Entities 2)"
    imageFromPoliticalEntities2: "fldFxyAstpoTQrd96", // Original field: "Image (from Political Entities 2)"
    periodFromFromPoliticalEntities2: "fldL3RQgi5v1j2PPi", // Original field: "Period From (from Political Entities 2)"
    periodToFromPoliticalEntities2: "fldtFvrcPEQo72Z0t", // Original field: "Period To (from Political Entities 2)"
    politicalEntities3: "fldS3O2SuXRS3gEnU", // Original field: "Political Entities 3"
    titleFromPoliticalEntities3: "fldkSptCa9gvNSXLB", // Original field: "Title (from Political Entities 3)"
  },
  schema: {
    documentName: "string | null",
    politicalEntity: "string[]",
    documents: "string[]",
    docSourceUrl: "string | null",
    language: "string | null",
    type: "string | null",
    processed: "boolean",
    status: "string | null",
    statusDate: "number | null",
    selectCountry: "string[]",
    nameFromCountries: "string | null",
    countryFromCountries: "string | null",
    politicalEntitiesFromCountries: "string[] | null",
    addAPoliticalEntity: "string[]",
    politicalEntityNameFromAddAPoliticalEntity: "string | null",
    countryFromAddAPoliticalEntity: "string[] | null",
    regionFromAddAPoliticalEntity: "string | null",
    titleFromAddAPoliticalEntity: "string | null",
    imageFromAddAPoliticalEntity: "string[] | null",
    periodFromFromAddAPoliticalEntity: "number | null",
    periodToFromAddAPoliticalEntity: "number | null",
    documentsFromAddAPoliticalEntity: "string[] | null",
    fromFieldCountriesFromAddAPoliticalEntity: "string | null",
    politicalEntities: "string[]",
    politicalEntityNameFromPoliticalEntities: "string | null",
    countryFromPoliticalEntities: "string[] | null",
    regionFromPoliticalEntities: "string | null",
    titleFromPoliticalEntities: "string | null",
    imageFromPoliticalEntities: "string[] | null",
    periodFromFromPoliticalEntities: "number | null",
    periodToFromPoliticalEntities: "number | null",
    politicalEntities2: "string[]",
    regionFromPoliticalEntities2: "string | null",
    titleFromPoliticalEntities2: "string | null",
    imageFromPoliticalEntities2: "string[] | null",
    periodFromFromPoliticalEntities2: "number | null",
    periodToFromPoliticalEntities2: "number | null",
    politicalEntities3: "string[]",
    titleFromPoliticalEntities3: "string | null",
  },
};

export interface CsoPromiseUpdate extends Item {
  id: string;
  promise: string | null; // Original field: "Promise"
  checkmediaLink: string | null; // Original field: "CheckMedia Link"
  date: number | null; // Original field: "Date"
  whatSYourUpdate: string | null; // Original field: "WHAT'S YOUR UPDATE?"
  whoElseCanConfirmYourUpdate: string | null; // Original field: "WHO ELSE CAN CONFIRM YOUR UPDATE?"
  whenDidTheUpdateHappen: string | null; // Original field: "WHEN DID THE UPDATE HAPPEN?"
  howDoWeContactYou: string | null; // Original field: "HOW DO WE CONTACT YOU?"
  whatEvidenceDoYouHave: string[]; // Original field: "WHAT EVIDENCE DO YOU HAVE?"
  createdBy: string; // Original field: "Created By"
}

export const CsoPromiseUpdatestable: Table<CsoPromiseUpdate> = {
  name: "CSO Promise Updates",
  baseId: "appIuU48pYIXtqDQg",
  tableId: "tblQ9n0yZJcJ2bFWI",
  mappings: {
    promise: "fldO3vKC7H319pkXj", // Original field: "Promise"
    checkmediaLink: "fld93ngZe9hTRPsFc", // Original field: "CheckMedia Link"
    date: "fldEdYCLkOimiXhh5", // Original field: "Date"
    whatSYourUpdate: "fldia3DbWRaCYbsgz", // Original field: "WHAT'S YOUR UPDATE?"
    whoElseCanConfirmYourUpdate: "fldyogCwEnoZBrVci", // Original field: "WHO ELSE CAN CONFIRM YOUR UPDATE?"
    whenDidTheUpdateHappen: "fldUIEtUfCAf400Wl", // Original field: "WHEN DID THE UPDATE HAPPEN?"
    howDoWeContactYou: "fldFxMQrYOW0ocbZA", // Original field: "HOW DO WE CONTACT YOU?"
    whatEvidenceDoYouHave: "fldk9HQYOJaBRRMdg", // Original field: "WHAT EVIDENCE DO YOU HAVE?"
    createdBy: "fldnKtCKlk6VBnv5H", // Original field: "Created By"
  },
  schema: {
    promise: "string | null",
    checkmediaLink: "string | null",
    date: "number | null",
    whatSYourUpdate: "string | null",
    whoElseCanConfirmYourUpdate: "string | null",
    whenDidTheUpdateHappen: "string | null",
    howDoWeContactYou: "string | null",
    whatEvidenceDoYouHave: "string[]",
    createdBy: "string",
  },
};
