/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    documents: Document;
    'ai-extractions': AiExtraction;
    'ai-extraction-export-rows': AiExtractionExportRow;
    promises: Promise;
    media: Media;
    pages: Page;
    'global-pages': GlobalPage;
    users: User;
    'site-settings': SiteSetting;
    tenants: Tenant;
    partners: Partner;
    'political-entities': PoliticalEntity;
    'promise-status': PromiseStatus;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'ai-extractions': AiExtractionsSelect<false> | AiExtractionsSelect<true>;
    'ai-extraction-export-rows': AiExtractionExportRowsSelect<false> | AiExtractionExportRowsSelect<true>;
    promises: PromisesSelect<false> | PromisesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'global-pages': GlobalPagesSelect<false> | GlobalPagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'political-entities': PoliticalEntitiesSelect<false> | PoliticalEntitiesSelect<true>;
    'promise-status': PromiseStatusSelect<false> | PromiseStatusSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr') | ('en' | 'fr')[];
  globals: {
    'entity-page': EntityPage;
    settings: Setting;
    'promise-updates': PromiseUpdate;
    'global-site-settings': GlobalSiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'entity-page': EntityPageSelect<false> | EntityPageSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'promise-updates': PromiseUpdatesSelect<false> | PromiseUpdatesSelect<true>;
    'global-site-settings': GlobalSiteSettingsSelect<false> | GlobalSiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'fr';
  user: User;
  jobs: {
    tasks: {
      createTenantFromAirtable: TaskCreateTenantFromAirtable;
      fetchAirtableDocuments: TaskFetchAirtableDocuments;
      downloadDocuments: TaskDownloadDocuments;
      extractDocuments: TaskExtractDocuments;
      extractPromises: TaskExtractPromises;
      uploadToMeedan: TaskUploadToMeedan;
      createPoliticalEntity: TaskCreatePoliticalEntity;
      fetchPromiseStatuses: TaskFetchPromiseStatuses;
      updatePromiseStatus: TaskUpdatePromiseStatus;
      syncMeedanPromises: TaskSyncMeedanPromises;
      syncAIExtractionExportRows: TaskSyncAIExtractionExportRows;
      cleanupFailedJobs: TaskCleanupFailedJobs;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      airtableWorkflow: WorkflowAirtableWorkflow;
      meedanWorkflow: WorkflowMeedanWorkflow;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  title: string;
  url?: string | null;
  docURLs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  files?: (string | Media)[] | null;
  politicalEntity?: (string | null) | PoliticalEntity;
  language?: ('en' | 'fr') | null;
  type?: ('promise' | 'evidence') | null;
  airtableID?: string | null;
  fullyProcessed?: boolean | null;
  extractedText?:
    | {
        text?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Original source URL for synced media
   */
  externalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "political-entities".
 */
export interface PoliticalEntity {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  slug: string;
  slugLock?: boolean | null;
  /**
   * Lower numbers appear first in listings.
   */
  order?: number | null;
  region?: string | null;
  /**
   * Title of the entity, i.e President, Governor, Prime Minister
   */
  position: string;
  /**
   * Image of the Political Entity
   */
  image: string | Media;
  periodFrom: string;
  periodTo: string;
  publish?: boolean | null;
  airtableID?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  locale: 'en' | 'fr';
  country:
    | 'DZA'
    | 'AGO'
    | 'BEN'
    | 'BWA'
    | 'IOT'
    | 'BFA'
    | 'BDI'
    | 'CPV'
    | 'CMR'
    | 'CAF'
    | 'TCD'
    | 'COM'
    | 'COG'
    | 'COD'
    | 'CIV'
    | 'DJI'
    | 'EGY'
    | 'GNQ'
    | 'ERI'
    | 'SWZ'
    | 'ETH'
    | 'ATF'
    | 'GAB'
    | 'GMB'
    | 'GHA'
    | 'GIN'
    | 'GNB'
    | 'KEN'
    | 'LSO'
    | 'LBR'
    | 'LBY'
    | 'MDG'
    | 'MWI'
    | 'MLI'
    | 'MRT'
    | 'MUS'
    | 'MYT'
    | 'MAR'
    | 'MOZ'
    | 'NAM'
    | 'NER'
    | 'NGA'
    | 'REU'
    | 'RWA'
    | 'SHN'
    | 'STP'
    | 'SEN'
    | 'SYC'
    | 'SLE'
    | 'SOM'
    | 'ZAF'
    | 'SSD'
    | 'SDN'
    | 'TZA'
    | 'TGO'
    | 'TUN'
    | 'UGA'
    | 'ESH'
    | 'ZMB'
    | 'ZWE';
  publish?: boolean | null;
  airtableID?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-extractions".
 */
export interface AiExtraction {
  id: string;
  title?: string | null;
  document: string | Document;
  extractions?:
    | {
        category: string;
        summary: string;
        source: string;
        uniqueId?: string | null;
        checkMediaId?: string | null;
        checkMediaURL?: string | null;
        Status?: (string | null) | PromiseStatus;
        /**
         * Set when the upload to Meedan fails permanently. Extractions with this field set will not be retried.
         */
        uploadError?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Status from CheckMedia
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promise-status".
 */
export interface PromiseStatus {
  id: string;
  label: string;
  meedanId: string;
  description: string;
  colors?: {
    color?: string | null;
    textColor?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-extraction-export-rows".
 */
export interface AiExtractionExportRow {
  id: string;
  uniqueKey: string;
  aiExtraction?: (string | null) | AiExtraction;
  document?: (string | null) | Document;
  politicalEntity?: (string | null) | PoliticalEntity;
  tenant?: (string | null) | Tenant;
  status?: (string | null) | PromiseStatus;
  tenantId?: string | null;
  tenantName?: string | null;
  tenantCountry?: string | null;
  tenantLocale?: string | null;
  politicalEntityId?: string | null;
  politicalEntityName?: string | null;
  politicalEntitySlug?: string | null;
  politicalEntityPosition?: string | null;
  documentId?: string | null;
  documentTitle?: string | null;
  documentUrl?: string | null;
  documentLanguage?: string | null;
  documentType?: string | null;
  documentAirtableID?: string | null;
  aiExtractionId?: string | null;
  aiExtractionTitle?: string | null;
  extractionRowId?: string | null;
  uniqueId?: string | null;
  category?: string | null;
  summary?: string | null;
  source?: string | null;
  statusId?: string | null;
  statusLabel?: string | null;
  statusMeedanId?: string | null;
  checkMediaId?: string | null;
  checkMediaURL?: string | null;
  uploadError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promises".
 */
export interface Promise {
  id: string;
  meedanId: string;
  title?: string | null;
  description?: string | null;
  url?: string | null;
  status?: (string | null) | PromiseStatus;
  politicalEntity?: (string | null) | PoliticalEntity;
  image?: (string | null) | Media;
  publishStatus?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  slug: string;
  slugLock?: boolean | null;
  blocks?:
    | (
        | ActNowBlock
        | FAQBlock
        | HeroBlock
        | KeyPromisesBlock
        | LatestPromisesBlock
        | NewsletterBlock
        | PageHeaderBlock
        | PartnersBlock
        | PartnerDetailsBlock
        | PromiseListBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActNowBlock".
 */
export interface ActNowBlock {
  logo: string | Media;
  description: string;
  image: string | Media;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'global-pages';
          value: string | GlobalPage;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'act-now';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-pages".
 */
export interface GlobalPage {
  id: string;
  title: string;
  slug: string;
  slugLock?: boolean | null;
  blocks?:
    | (
        | ActNowBlock
        | FAQBlock
        | NewsletterBlock
        | PageHeaderBlock
        | PartnersBlock
        | PartnerDetailsBlock
        | TenantSelectorBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title: string;
  faqs: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'page-header';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  title: string;
  partners?: (string | Partner)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: string | Media;
  url: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'global-pages';
          value: string | GlobalPage;
        } | null);
    url?: string | null;
    label: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerDetailsBlock".
 */
export interface PartnerDetailsBlock {
  partners: (string | Partner)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'partner-details';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TenantSelectorBlock".
 */
export interface TenantSelectorBlock {
  title: string;
  subtitle: string;
  ctaLabel: string;
  emptyListLabel: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tenant-selection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Displayed alongside the political entity name in the hero.
   */
  tagline?: string | null;
  /**
   * Label displayed beside the total count of synced promises.
   */
  promiseLabel?: string | null;
  /**
   * Sentence that follows the promise count, for example 'tracked on PromiseTracker'.
   */
  trailText?: string | null;
  updatedAtLabel?: string | null;
  /**
   * Optional text that replaces the political entity position shown above the last updated date.
   */
  profileTitleOverride?: string | null;
  statusListTitle?: string | null;
  /**
   * Define exactly three groups of promise statuses to display in the charts.
   */
  chartGroups: {
    title: string;
    statuses: (string | PromiseStatus)[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyPromisesBlock".
 */
export interface KeyPromisesBlock {
  title: string;
  actionLabel?: string | null;
  /**
   * How many highlighted promises to display (minimum 1).
   */
  itemsToShow: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'key-promises';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPromisesBlock".
 */
export interface LatestPromisesBlock {
  title: string;
  /**
   * Link to the page where all promises can be viewed. E.g. /promises
   */
  seeAllLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'global-pages';
          value: string | GlobalPage;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'latest-promises';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromiseListBlock".
 */
export interface PromiseListBlock {
  title?: string | null;
  filterByLabel?: string | null;
  sortByLabel?: string | null;
  filterBy?: ('status' | 'category')[] | null;
  sortBy?: ('mostRecent' | 'deadline')[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promise-list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  tenants?:
    | {
        tenant: string | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown on main navigation bar.
   */
  primaryLogo: string | Media;
  /**
   * Shown on main footer. If not provided, primary logo will be reused.
   */
  secondaryLogo: string | Media;
  /**
   * Shown on secondary footer. If not provided, secondary logo will be reused.
   */
  alternateLogo: string | Media;
  legal?: {
    copyright?: string | null;
    /**
     * Links to legal information, for example, terms of service or privacy policy
     */
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'global-pages';
                  value: string | GlobalPage;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  primaryNavigation?: {
    titles?: string | null;
    menus?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'global-pages';
                  value: string | GlobalPage;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  secondaryNavigationList?:
    | {
        secondaryNavigation?: {
          titles?: string | null;
          menus?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'global-pages';
                        value: string | GlobalPage;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  connect: {
    /**
     * Text that appears on contact links e.g Stay in Touch
     */
    title: string;
    links?:
      | {
          platform: 'Facebook' | 'Twitter' | 'Instagram' | 'Linkedin' | 'Github' | 'Slack';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  newsletter: {
    title: string;
    description: string;
    embedCode: string;
  };
  actNow: {
    title: string;
    share: {
      title: string;
      description: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'en' | 'fr') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'createTenantFromAirtable'
          | 'fetchAirtableDocuments'
          | 'downloadDocuments'
          | 'extractDocuments'
          | 'extractPromises'
          | 'uploadToMeedan'
          | 'createPoliticalEntity'
          | 'fetchPromiseStatuses'
          | 'updatePromiseStatus'
          | 'syncMeedanPromises'
          | 'syncAIExtractionExportRows'
          | 'cleanupFailedJobs'
          | 'createCollectionExport'
          | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        parent?: {
          taskSlug?:
            | (
                | 'inline'
                | 'createTenantFromAirtable'
                | 'fetchAirtableDocuments'
                | 'downloadDocuments'
                | 'extractDocuments'
                | 'extractPromises'
                | 'uploadToMeedan'
                | 'createPoliticalEntity'
                | 'fetchPromiseStatuses'
                | 'updatePromiseStatus'
                | 'syncMeedanPromises'
                | 'syncAIExtractionExportRows'
                | 'cleanupFailedJobs'
                | 'createCollectionExport'
                | 'createCollectionImport'
              )
            | null;
          taskID?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  workflowSlug?: ('airtableWorkflow' | 'meedanWorkflow') | null;
  taskSlug?:
    | (
        | 'inline'
        | 'createTenantFromAirtable'
        | 'fetchAirtableDocuments'
        | 'downloadDocuments'
        | 'extractDocuments'
        | 'extractPromises'
        | 'uploadToMeedan'
        | 'createPoliticalEntity'
        | 'fetchPromiseStatuses'
        | 'updatePromiseStatus'
        | 'syncMeedanPromises'
        | 'syncAIExtractionExportRows'
        | 'cleanupFailedJobs'
        | 'createCollectionExport'
        | 'createCollectionImport'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'ai-extractions';
        value: string | AiExtraction;
      } | null)
    | ({
        relationTo: 'ai-extraction-export-rows';
        value: string | AiExtractionExportRow;
      } | null)
    | ({
        relationTo: 'promises';
        value: string | Promise;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'global-pages';
        value: string | GlobalPage;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: string | SiteSetting;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'political-entities';
        value: string | PoliticalEntity;
      } | null)
    | ({
        relationTo: 'promise-status';
        value: string | PromiseStatus;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  docURLs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  files?: T;
  politicalEntity?: T;
  language?: T;
  type?: T;
  airtableID?: T;
  fullyProcessed?: T;
  extractedText?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-extractions_select".
 */
export interface AiExtractionsSelect<T extends boolean = true> {
  title?: T;
  document?: T;
  extractions?:
    | T
    | {
        category?: T;
        summary?: T;
        source?: T;
        uniqueId?: T;
        checkMediaId?: T;
        checkMediaURL?: T;
        Status?: T;
        uploadError?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-extraction-export-rows_select".
 */
export interface AiExtractionExportRowsSelect<T extends boolean = true> {
  uniqueKey?: T;
  aiExtraction?: T;
  document?: T;
  politicalEntity?: T;
  tenant?: T;
  status?: T;
  tenantId?: T;
  tenantName?: T;
  tenantCountry?: T;
  tenantLocale?: T;
  politicalEntityId?: T;
  politicalEntityName?: T;
  politicalEntitySlug?: T;
  politicalEntityPosition?: T;
  documentId?: T;
  documentTitle?: T;
  documentUrl?: T;
  documentLanguage?: T;
  documentType?: T;
  documentAirtableID?: T;
  aiExtractionId?: T;
  aiExtractionTitle?: T;
  extractionRowId?: T;
  uniqueId?: T;
  category?: T;
  summary?: T;
  source?: T;
  statusId?: T;
  statusLabel?: T;
  statusMeedanId?: T;
  checkMediaId?: T;
  checkMediaURL?: T;
  uploadError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promises_select".
 */
export interface PromisesSelect<T extends boolean = true> {
  meedanId?: T;
  title?: T;
  description?: T;
  url?: T;
  status?: T;
  politicalEntity?: T;
  image?: T;
  publishStatus?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  externalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  blocks?:
    | T
    | {
        'act-now'?: T | ActNowBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        hero?: T | HeroBlockSelect<T>;
        'key-promises'?: T | KeyPromisesBlockSelect<T>;
        'latest-promises'?: T | LatestPromisesBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        'page-header'?: T | PageHeaderBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        'partner-details'?: T | PartnerDetailsBlockSelect<T>;
        'promise-list'?: T | PromiseListBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActNowBlock_select".
 */
export interface ActNowBlockSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  image?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  tagline?: T;
  promiseLabel?: T;
  trailText?: T;
  updatedAtLabel?: T;
  profileTitleOverride?: T;
  statusListTitle?: T;
  chartGroups?:
    | T
    | {
        title?: T;
        statuses?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyPromisesBlock_select".
 */
export interface KeyPromisesBlockSelect<T extends boolean = true> {
  title?: T;
  actionLabel?: T;
  itemsToShow?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPromisesBlock_select".
 */
export interface LatestPromisesBlockSelect<T extends boolean = true> {
  title?: T;
  seeAllLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  title?: T;
  partners?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerDetailsBlock_select".
 */
export interface PartnerDetailsBlockSelect<T extends boolean = true> {
  partners?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromiseListBlock_select".
 */
export interface PromiseListBlockSelect<T extends boolean = true> {
  title?: T;
  filterByLabel?: T;
  sortByLabel?: T;
  filterBy?: T;
  sortBy?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-pages_select".
 */
export interface GlobalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  blocks?:
    | T
    | {
        'act-now'?: T | ActNowBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        'page-header'?: T | PageHeaderBlockSelect<T>;
        partners?: T | PartnersBlockSelect<T>;
        'partner-details'?: T | PartnerDetailsBlockSelect<T>;
        'tenant-selection'?: T | TenantSelectorBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TenantSelectorBlock_select".
 */
export interface TenantSelectorBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaLabel?: T;
  emptyListLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  primaryLogo?: T;
  secondaryLogo?: T;
  alternateLogo?: T;
  legal?:
    | T
    | {
        copyright?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  primaryNavigation?:
    | T
    | {
        titles?: T;
        menus?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  secondaryNavigationList?:
    | T
    | {
        secondaryNavigation?:
          | T
          | {
              titles?: T;
              menus?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  connect?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        embedCode?: T;
      };
  actNow?:
    | T
    | {
        title?: T;
        share?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  locale?: T;
  country?: T;
  publish?: T;
  airtableID?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  url?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "political-entities_select".
 */
export interface PoliticalEntitiesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  slugLock?: T;
  order?: T;
  region?: T;
  position?: T;
  image?: T;
  periodFrom?: T;
  periodTo?: T;
  publish?: T;
  airtableID?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promise-status_select".
 */
export interface PromiseStatusSelect<T extends boolean = true> {
  label?: T;
  meedanId?: T;
  description?: T;
  colors?:
    | T
    | {
        color?: T;
        textColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        parent?:
          | T
          | {
              taskSlug?: T;
              taskID?: T;
            };
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entity-page".
 */
export interface EntityPage {
  id: string;
  entitySelector: {
    blocks: (ActNowBlock | EntitySelectionBlock | EntityHeroBlock | NewsletterBlock | PartnersBlock)[];
  };
  primaryNavigation?: {
    titles?: string | null;
    menus?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'global-pages';
                  value: string | GlobalPage;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  secondaryNavigationList?:
    | {
        secondaryNavigation?: {
          titles?: string | null;
          menus?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'global-pages';
                        value: string | GlobalPage;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntitySelectionBlock".
 */
export interface EntitySelectionBlock {
  title: string;
  emptyTitle: string;
  EmptySubtitle: string;
  /**
   * Select promise statuses to highlight in entity lists and hero sections.
   */
  statusGroups?:
    | {
        title: string;
        description: string;
        color: string;
        statuses: (string | PromiseStatus)[];
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entity-selection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntityHeroBlock".
 */
export interface EntityHeroBlock {
  title: string;
  description: string;
  carousel: {
    carouselItems?: {
      images?: (string | Media)[] | null;
      tenant?: (string | null) | Tenant;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'entity-hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  airtable: {
    airtableAPIKey: string;
    airtableBaseID: string;
  };
  ai: {
    /**
     * Add credentials first. Only configured providers can be selected for extraction models.
     */
    providerCredentials?:
      | {
          provider:
            | 'google'
            | 'xai'
            | 'openai'
            | 'anthropic'
            | 'mistral'
            | 'deepseek'
            | 'cerebras'
            | 'groq'
            | 'togetherai'
            | 'cohere'
            | 'fireworks'
            | 'deepinfra'
            | 'perplexity'
            | 'ollama';
          /**
           * Optional if configured in environment variables. Saved keys are validated when possible.
           */
          apiKey?: string | null;
          /**
           * Optional Ollama base URL (e.g. http://localhost:11434).
           */
          baseURL?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Only providers with credentials configured in Settings or environment are listed.
     */
    modelProvider:
      | 'google'
      | 'xai'
      | 'openai'
      | 'anthropic'
      | 'mistral'
      | 'deepseek'
      | 'cerebras'
      | 'groq'
      | 'togetherai'
      | 'cohere'
      | 'fireworks'
      | 'deepinfra'
      | 'perplexity'
      | 'ollama';
    /**
     * Model suggestions are inferred from installed AI SDK provider model IDs.
     */
    modelPreset?:
      | (
          | 'google:gemini-1.5-flash'
          | 'google:gemini-1.5-flash-latest'
          | 'google:gemini-1.5-flash-001'
          | 'google:gemini-1.5-flash-002'
          | 'google:gemini-1.5-flash-8b'
          | 'google:gemini-1.5-flash-8b-latest'
          | 'google:gemini-1.5-flash-8b-001'
          | 'google:gemini-1.5-pro'
          | 'google:gemini-1.5-pro-latest'
          | 'google:gemini-1.5-pro-001'
          | 'google:gemini-1.5-pro-002'
          | 'google:gemini-2.0-flash'
          | 'google:gemini-2.0-flash-001'
          | 'google:gemini-2.0-flash-live-001'
          | 'google:gemini-2.0-flash-lite'
          | 'google:gemini-2.0-pro-exp-02-05'
          | 'google:gemini-2.0-flash-thinking-exp-01-21'
          | 'google:gemini-2.0-flash-exp'
          | 'google:gemini-2.5-pro'
          | 'google:gemini-2.5-flash'
          | 'google:gemini-2.5-flash-image'
          | 'google:gemini-2.5-flash-lite'
          | 'google:gemini-2.5-flash-lite-preview-09-2025'
          | 'google:gemini-2.5-flash-preview-04-17'
          | 'google:gemini-2.5-flash-preview-09-2025'
          | 'google:gemini-3.1-pro-preview'
          | 'google:gemini-3-pro-preview'
          | 'google:gemini-3-pro-image-preview'
          | 'google:gemini-3-flash-preview'
          | 'google:gemini-pro-latest'
          | 'google:gemini-flash-latest'
          | 'google:gemini-flash-lite-latest'
          | 'google:gemini-2.5-pro-exp-03-25'
          | 'google:gemini-exp-1206'
          | 'google:gemma-3-12b-it'
          | 'google:gemma-3-27b-it'
          | 'xai:grok-4-1-fast-reasoning'
          | 'xai:grok-4-1-fast-non-reasoning'
          | 'xai:grok-4-fast-non-reasoning'
          | 'xai:grok-4-fast-reasoning'
          | 'xai:grok-code-fast-1'
          | 'xai:grok-4'
          | 'xai:grok-4-0709'
          | 'xai:grok-4-latest'
          | 'xai:grok-3'
          | 'xai:grok-3-latest'
          | 'xai:grok-3-fast'
          | 'xai:grok-3-fast-latest'
          | 'xai:grok-3-mini'
          | 'xai:grok-3-mini-latest'
          | 'xai:grok-3-mini-fast'
          | 'xai:grok-3-mini-fast-latest'
          | 'xai:grok-2-vision-1212'
          | 'xai:grok-2-vision'
          | 'xai:grok-2-vision-latest'
          | 'xai:grok-2-image-1212'
          | 'xai:grok-2-image'
          | 'xai:grok-2-image-latest'
          | 'xai:grok-2-1212'
          | 'xai:grok-2'
          | 'xai:grok-2-latest'
          | 'xai:grok-vision-beta'
          | 'xai:grok-beta'
          | 'openai:o1'
          | 'openai:o1-2024-12-17'
          | 'openai:o3-mini'
          | 'openai:o3-mini-2025-01-31'
          | 'openai:o3'
          | 'openai:o3-2025-04-16'
          | 'openai:o4-mini'
          | 'openai:o4-mini-2025-04-16'
          | 'openai:gpt-4.1'
          | 'openai:gpt-4.1-2025-04-14'
          | 'openai:gpt-4.1-mini'
          | 'openai:gpt-4.1-mini-2025-04-14'
          | 'openai:gpt-4.1-nano'
          | 'openai:gpt-4.1-nano-2025-04-14'
          | 'openai:gpt-4o'
          | 'openai:gpt-4o-2024-05-13'
          | 'openai:gpt-4o-2024-08-06'
          | 'openai:gpt-4o-2024-11-20'
          | 'openai:gpt-4o-mini'
          | 'openai:gpt-4o-mini-2024-07-18'
          | 'openai:gpt-4-turbo'
          | 'openai:gpt-4-turbo-2024-04-09'
          | 'openai:gpt-4'
          | 'openai:gpt-4-0613'
          | 'openai:gpt-4.5-preview'
          | 'openai:gpt-4.5-preview-2025-02-27'
          | 'openai:gpt-3.5-turbo-0125'
          | 'openai:gpt-3.5-turbo'
          | 'openai:gpt-3.5-turbo-1106'
          | 'openai:chatgpt-4o-latest'
          | 'openai:gpt-5'
          | 'openai:gpt-5-2025-08-07'
          | 'openai:gpt-5-mini'
          | 'openai:gpt-5-mini-2025-08-07'
          | 'openai:gpt-5-nano'
          | 'openai:gpt-5-nano-2025-08-07'
          | 'openai:gpt-5-chat-latest'
          | 'openai:gpt-5.1'
          | 'openai:gpt-5.1-chat-latest'
          | 'openai:gpt-5.2'
          | 'openai:gpt-5.2-chat-latest'
          | 'openai:gpt-5.2-pro'
          | 'anthropic:claude-3-5-haiku-20241022'
          | 'anthropic:claude-3-5-haiku-latest'
          | 'anthropic:claude-3-7-sonnet-20250219'
          | 'anthropic:claude-3-7-sonnet-latest'
          | 'anthropic:claude-3-haiku-20240307'
          | 'anthropic:claude-haiku-4-5-20251001'
          | 'anthropic:claude-haiku-4-5'
          | 'anthropic:claude-opus-4-0'
          | 'anthropic:claude-opus-4-1-20250805'
          | 'anthropic:claude-opus-4-1'
          | 'anthropic:claude-opus-4-20250514'
          | 'anthropic:claude-opus-4-5'
          | 'anthropic:claude-opus-4-5-20251101'
          | 'anthropic:claude-sonnet-4-0'
          | 'anthropic:claude-sonnet-4-20250514'
          | 'anthropic:claude-sonnet-4-5-20250929'
          | 'anthropic:claude-sonnet-4-5'
          | 'anthropic:claude-sonnet-4-6'
          | 'anthropic:claude-opus-4-6'
          | 'mistral:ministral-3b-latest'
          | 'mistral:ministral-8b-latest'
          | 'mistral:mistral-large-latest'
          | 'mistral:mistral-medium-latest'
          | 'mistral:mistral-medium-2508'
          | 'mistral:mistral-medium-2505'
          | 'mistral:mistral-small-latest'
          | 'mistral:pixtral-large-latest'
          | 'mistral:magistral-small-2507'
          | 'mistral:magistral-medium-2507'
          | 'mistral:magistral-small-2506'
          | 'mistral:magistral-medium-2506'
          | 'mistral:pixtral-12b-2409'
          | 'mistral:open-mistral-7b'
          | 'mistral:open-mixtral-8x7b'
          | 'mistral:open-mixtral-8x22b'
          | 'deepseek:deepseek-chat'
          | 'deepseek:deepseek-reasoner'
          | 'cerebras:llama3.1-8b'
          | 'cerebras:gpt-oss-120b'
          | 'cerebras:qwen-3-235b-a22b-instruct-2507'
          | 'cerebras:qwen-3-235b-a22b-thinking-2507'
          | 'cerebras:zai-glm-4.6'
          | 'cerebras:zai-glm-4.7'
          | 'groq:gemma2-9b-it'
          | 'groq:llama-3.1-8b-instant'
          | 'groq:llama-3.3-70b-versatile'
          | 'groq:meta-llama/llama-guard-4-12b'
          | 'groq:openai/gpt-oss-120b'
          | 'groq:openai/gpt-oss-20b'
          | 'groq:deepseek-r1-distill-llama-70b'
          | 'groq:meta-llama/llama-4-maverick-17b-128e-instruct'
          | 'groq:meta-llama/llama-4-scout-17b-16e-instruct'
          | 'groq:meta-llama/llama-prompt-guard-2-22m'
          | 'groq:meta-llama/llama-prompt-guard-2-86m'
          | 'groq:moonshotai/kimi-k2-instruct-0905'
          | 'groq:qwen/qwen3-32b'
          | 'groq:llama-guard-3-8b'
          | 'groq:llama3-70b-8192'
          | 'groq:llama3-8b-8192'
          | 'groq:mixtral-8x7b-32768'
          | 'groq:qwen-qwq-32b'
          | 'groq:qwen-2.5-32b'
          | 'groq:deepseek-r1-distill-qwen-32b'
          | 'togetherai:meta-llama/Llama-3.3-70B-Instruct-Turbo'
          | 'togetherai:meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'
          | 'togetherai:meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'
          | 'togetherai:meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo'
          | 'togetherai:meta-llama/Meta-Llama-3-8B-Instruct-Turbo'
          | 'togetherai:meta-llama/Meta-Llama-3-70B-Instruct-Turbo'
          | 'togetherai:meta-llama/Llama-3.2-3B-Instruct-Turbo'
          | 'togetherai:meta-llama/Meta-Llama-3-8B-Instruct-Lite'
          | 'togetherai:meta-llama/Meta-Llama-3-70B-Instruct-Lite'
          | 'togetherai:meta-llama/Llama-3-8b-chat-hf'
          | 'togetherai:meta-llama/Llama-3-70b-chat-hf'
          | 'togetherai:nvidia/Llama-3.1-Nemotron-70B-Instruct-HF'
          | 'togetherai:Qwen/Qwen2.5-Coder-32B-Instruct'
          | 'togetherai:Qwen/QwQ-32B-Preview'
          | 'togetherai:microsoft/WizardLM-2-8x22B'
          | 'togetherai:google/gemma-2-27b-it'
          | 'togetherai:google/gemma-2-9b-it'
          | 'togetherai:databricks/dbrx-instruct'
          | 'togetherai:deepseek-ai/deepseek-llm-67b-chat'
          | 'togetherai:deepseek-ai/DeepSeek-V3'
          | 'togetherai:google/gemma-2b-it'
          | 'togetherai:Gryphe/MythoMax-L2-13b'
          | 'togetherai:meta-llama/Llama-2-13b-chat-hf'
          | 'togetherai:mistralai/Mistral-7B-Instruct-v0.1'
          | 'togetherai:mistralai/Mistral-7B-Instruct-v0.2'
          | 'togetherai:mistralai/Mistral-7B-Instruct-v0.3'
          | 'togetherai:mistralai/Mixtral-8x7B-Instruct-v0.1'
          | 'togetherai:mistralai/Mixtral-8x22B-Instruct-v0.1'
          | 'togetherai:NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO'
          | 'togetherai:Qwen/Qwen2.5-7B-Instruct-Turbo'
          | 'togetherai:Qwen/Qwen2.5-72B-Instruct-Turbo'
          | 'togetherai:Qwen/Qwen2-72B-Instruct'
          | 'togetherai:upstage/SOLAR-10.7B-Instruct-v1.0'
          | 'cohere:command-a-03-2025'
          | 'cohere:command-a-reasoning-08-2025'
          | 'cohere:command-r7b-12-2024'
          | 'cohere:command-r-plus-04-2024'
          | 'cohere:command-r-plus'
          | 'cohere:command-r-08-2024'
          | 'cohere:command-r-03-2024'
          | 'cohere:command-r'
          | 'cohere:command'
          | 'cohere:command-nightly'
          | 'cohere:command-light'
          | 'cohere:command-light-nightly'
          | 'fireworks:accounts/fireworks/models/deepseek-v3'
          | 'fireworks:accounts/fireworks/models/llama-v3p3-70b-instruct'
          | 'fireworks:accounts/fireworks/models/llama-v3p2-3b-instruct'
          | 'fireworks:accounts/fireworks/models/llama-v3p1-405b-instruct'
          | 'fireworks:accounts/fireworks/models/llama-v3p1-8b-instruct'
          | 'fireworks:accounts/fireworks/models/mixtral-8x7b-instruct'
          | 'fireworks:accounts/fireworks/models/mixtral-8x22b-instruct'
          | 'fireworks:accounts/fireworks/models/mixtral-8x7b-instruct-hf'
          | 'fireworks:accounts/fireworks/models/qwen2p5-coder-32b-instruct'
          | 'fireworks:accounts/fireworks/models/qwen2p5-72b-instruct'
          | 'fireworks:accounts/fireworks/models/qwen-qwq-32b-preview'
          | 'fireworks:accounts/fireworks/models/qwen2-vl-72b-instruct'
          | 'fireworks:accounts/fireworks/models/llama-v3p2-11b-vision-instruct'
          | 'fireworks:accounts/fireworks/models/qwq-32b'
          | 'fireworks:accounts/fireworks/models/yi-large'
          | 'fireworks:accounts/fireworks/models/kimi-k2-instruct'
          | 'fireworks:accounts/fireworks/models/kimi-k2-thinking'
          | 'fireworks:accounts/fireworks/models/kimi-k2p5'
          | 'fireworks:accounts/fireworks/models/minimax-m2'
          | 'deepinfra:01-ai/Yi-34B-Chat'
          | 'deepinfra:Austism/chronos-hermes-13b-v2'
          | 'deepinfra:bigcode/starcoder2-15b-instruct-v0.1'
          | 'deepinfra:bigcode/starcoder2-15b'
          | 'deepinfra:codellama/CodeLlama-34b-Instruct-hf'
          | 'deepinfra:codellama/CodeLlama-70b-Instruct-hf'
          | 'deepinfra:cognitivecomputations/dolphin-2.6-mixtral-8x7b'
          | 'deepinfra:cognitivecomputations/dolphin-2.9.1-llama-3-70b'
          | 'deepinfra:databricks/dbrx-instruct'
          | 'deepinfra:deepinfra/airoboros-70b'
          | 'deepinfra:deepseek-ai/DeepSeek-V3'
          | 'deepinfra:google/codegemma-7b-it'
          | 'deepinfra:google/gemma-1.1-7b-it'
          | 'deepinfra:google/gemma-2-27b-it'
          | 'deepinfra:google/gemma-2-9b-it'
          | 'deepinfra:Gryphe/MythoMax-L2-13b-turbo'
          | 'deepinfra:Gryphe/MythoMax-L2-13b'
          | 'deepinfra:HuggingFaceH4/zephyr-orpo-141b-A35b-v0.1'
          | 'deepinfra:KoboldAI/LLaMA2-13B-Tiefighter'
          | 'deepinfra:lizpreciatior/lzlv_70b_fp16_hf'
          | 'deepinfra:mattshumer/Reflection-Llama-3.1-70B'
          | 'deepinfra:meta-llama/Llama-2-13b-chat-hf'
          | 'deepinfra:meta-llama/Llama-2-70b-chat-hf'
          | 'deepinfra:meta-llama/Llama-2-7b-chat-hf'
          | 'deepinfra:meta-llama/Llama-3.2-11B-Vision-Instruct'
          | 'deepinfra:meta-llama/Llama-3.2-1B-Instruct'
          | 'deepinfra:meta-llama/Llama-3.2-3B-Instruct'
          | 'deepinfra:meta-llama/Llama-3.2-90B-Vision-Instruct'
          | 'deepinfra:meta-llama/Llama-3.3-70B-Instruct-Turbo'
          | 'deepinfra:meta-llama/Llama-3.3-70B-Instruct'
          | 'deepinfra:meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8'
          | 'deepinfra:meta-llama/Llama-4-Scout-17B-16E-Instruct'
          | 'deepinfra:meta-llama/Meta-Llama-3-70B-Instruct'
          | 'deepinfra:meta-llama/Meta-Llama-3-8B-Instruct'
          | 'deepinfra:meta-llama/Meta-Llama-3.1-405B-Instruct'
          | 'deepinfra:meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo'
          | 'deepinfra:meta-llama/Meta-Llama-3.1-70B-Instruct'
          | 'deepinfra:meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'
          | 'deepinfra:meta-llama/Meta-Llama-3.1-8B-Instruct'
          | 'deepinfra:microsoft/Phi-3-medium-4k-instruct'
          | 'deepinfra:microsoft/WizardLM-2-7B'
          | 'deepinfra:microsoft/WizardLM-2-8x22B'
          | 'deepinfra:mistralai/Mistral-7B-Instruct-v0.1'
          | 'deepinfra:mistralai/Mistral-7B-Instruct-v0.2'
          | 'deepinfra:mistralai/Mistral-7B-Instruct-v0.3'
          | 'deepinfra:mistralai/Mistral-Nemo-Instruct-2407'
          | 'deepinfra:mistralai/Mixtral-8x22B-Instruct-v0.1'
          | 'deepinfra:mistralai/Mixtral-8x22B-v0.1'
          | 'deepinfra:mistralai/Mixtral-8x7B-Instruct-v0.1'
          | 'deepinfra:NousResearch/Hermes-3-Llama-3.1-405B'
          | 'deepinfra:nvidia/Llama-3.1-Nemotron-70B-Instruct'
          | 'deepinfra:nvidia/Nemotron-4-340B-Instruct'
          | 'deepinfra:openbmb/MiniCPM-Llama3-V-2_5'
          | 'deepinfra:openchat/openchat_3.5'
          | 'deepinfra:openchat/openchat-3.6-8b'
          | 'deepinfra:Phind/Phind-CodeLlama-34B-v2'
          | 'deepinfra:Qwen/Qwen2-72B-Instruct'
          | 'deepinfra:Qwen/Qwen2-7B-Instruct'
          | 'deepinfra:Qwen/Qwen2.5-72B-Instruct'
          | 'deepinfra:Qwen/Qwen2.5-7B-Instruct'
          | 'deepinfra:Qwen/Qwen2.5-Coder-32B-Instruct'
          | 'deepinfra:Qwen/Qwen2.5-Coder-7B'
          | 'deepinfra:Qwen/QwQ-32B-Preview'
          | 'deepinfra:Sao10K/L3-70B-Euryale-v2.1'
          | 'deepinfra:Sao10K/L3-8B-Lunaris-v1'
          | 'deepinfra:Sao10K/L3.1-70B-Euryale-v2.2'
          | 'perplexity:sonar-deep-research'
          | 'perplexity:sonar-reasoning-pro'
          | 'perplexity:sonar-reasoning'
          | 'perplexity:sonar-pro'
          | 'perplexity:sonar'
        )
      | null;
    /**
     * Optional override in "provider:model" format. Must match the selected provider.
     */
    customModelId?: string | null;
    model?: ('gemini-2.5-pro' | 'gemini-2.5-flash-lite') | null;
    apiKey?: string | null;
  };
  meedan: {
    meedanAPIKey: string;
    teamId: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promise-updates".
 */
export interface PromiseUpdate {
  id: string;
  /**
   * The default image that should be used for a promise.
   */
  defaultImage: string | Media;
  /**
   * Paste the Airtable embed snippet that should appear inside the update dialog.
   */
  embedCode: string;
  /**
   * The label that should appear on the update dialog trigger button.
   */
  updateLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-site-settings".
 */
export interface GlobalSiteSetting {
  id: string;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Shown on main navigation bar.
   */
  primaryLogo: string | Media;
  /**
   * Shown on main footer. If not provided, primary logo will be reused.
   */
  secondaryLogo: string | Media;
  /**
   * Shown on secondary footer. If not provided, secondary logo will be reused.
   */
  alternateLogo: string | Media;
  legal?: {
    copyright?: string | null;
    /**
     * Links to legal information, for example, terms of service or privacy policy
     */
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'global-pages';
                  value: string | GlobalPage;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  primaryNavigation?: {
    titles?: string | null;
    menus?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'global-pages';
                  value: string | GlobalPage;
                } | null);
            url?: string | null;
            label: string;
          };
          id?: string | null;
        }[]
      | null;
  };
  secondaryNavigationList?:
    | {
        secondaryNavigation?: {
          titles?: string | null;
          menus?:
            | {
                link: {
                  type?: ('reference' | 'custom') | null;
                  newTab?: boolean | null;
                  reference?:
                    | ({
                        relationTo: 'pages';
                        value: string | Page;
                      } | null)
                    | ({
                        relationTo: 'global-pages';
                        value: string | GlobalPage;
                      } | null);
                  url?: string | null;
                  label: string;
                };
                id?: string | null;
              }[]
            | null;
        };
        id?: string | null;
      }[]
    | null;
  connect: {
    /**
     * Text that appears on contact links e.g Stay in Touch
     */
    title: string;
    links?:
      | {
          platform: 'Facebook' | 'Twitter' | 'Instagram' | 'Linkedin' | 'Github' | 'Slack';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  newsletter: {
    title: string;
    description: string;
    embedCode: string;
  };
  actNow: {
    title: string;
    share: {
      title: string;
      description: string;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entity-page_select".
 */
export interface EntityPageSelect<T extends boolean = true> {
  entitySelector?:
    | T
    | {
        blocks?:
          | T
          | {
              'act-now'?: T | ActNowBlockSelect<T>;
              'entity-selection'?: T | EntitySelectionBlockSelect<T>;
              'entity-hero'?: T | EntityHeroBlockSelect<T>;
              newsletter?: T | NewsletterBlockSelect<T>;
              partners?: T | PartnersBlockSelect<T>;
            };
      };
  primaryNavigation?:
    | T
    | {
        titles?: T;
        menus?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  secondaryNavigationList?:
    | T
    | {
        secondaryNavigation?:
          | T
          | {
              titles?: T;
              menus?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntitySelectionBlock_select".
 */
export interface EntitySelectionBlockSelect<T extends boolean = true> {
  title?: T;
  emptyTitle?: T;
  EmptySubtitle?: T;
  statusGroups?:
    | T
    | {
        title?: T;
        description?: T;
        color?: T;
        statuses?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntityHeroBlock_select".
 */
export interface EntityHeroBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  carousel?:
    | T
    | {
        carouselItems?:
          | T
          | {
              images?: T;
              tenant?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  airtable?:
    | T
    | {
        airtableAPIKey?: T;
        airtableBaseID?: T;
      };
  ai?:
    | T
    | {
        providerCredentials?:
          | T
          | {
              provider?: T;
              apiKey?: T;
              baseURL?: T;
              id?: T;
            };
        modelProvider?: T;
        modelPreset?: T;
        customModelId?: T;
        model?: T;
        apiKey?: T;
      };
  meedan?:
    | T
    | {
        meedanAPIKey?: T;
        teamId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promise-updates_select".
 */
export interface PromiseUpdatesSelect<T extends boolean = true> {
  defaultImage?: T;
  embedCode?: T;
  updateLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-site-settings_select".
 */
export interface GlobalSiteSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  primaryLogo?: T;
  secondaryLogo?: T;
  alternateLogo?: T;
  legal?:
    | T
    | {
        copyright?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  primaryNavigation?:
    | T
    | {
        titles?: T;
        menus?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  secondaryNavigationList?:
    | T
    | {
        secondaryNavigation?:
          | T
          | {
              titles?: T;
              menus?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
            };
        id?: T;
      };
  connect?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        title?: T;
        description?: T;
        embedCode?: T;
      };
  actNow?:
    | T
    | {
        title?: T;
        share?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateTenantFromAirtable".
 */
export interface TaskCreateTenantFromAirtable {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFetchAirtableDocuments".
 */
export interface TaskFetchAirtableDocuments {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDownloadDocuments".
 */
export interface TaskDownloadDocuments {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExtractDocuments".
 */
export interface TaskExtractDocuments {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExtractPromises".
 */
export interface TaskExtractPromises {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUploadToMeedan".
 */
export interface TaskUploadToMeedan {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreatePoliticalEntity".
 */
export interface TaskCreatePoliticalEntity {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskFetchPromiseStatuses".
 */
export interface TaskFetchPromiseStatuses {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskUpdatePromiseStatus".
 */
export interface TaskUpdatePromiseStatus {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncMeedanPromises".
 */
export interface TaskSyncMeedanPromises {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncAIExtractionExportRows".
 */
export interface TaskSyncAIExtractionExportRows {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanupFailedJobs".
 */
export interface TaskCleanupFailedJobs {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format: 'csv' | 'json';
    limit?: number | null;
    page?: number | null;
    sort?: string | null;
    sortOrder?: ('asc' | 'desc') | null;
    locale?: ('all' | 'en' | 'fr') | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
    batchSize?: number | null;
    userID?: string | null;
    userCollection?: string | null;
    exportCollection?: string | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowAirtableWorkflow".
 */
export interface WorkflowAirtableWorkflow {
  input?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowMeedanWorkflow".
 */
export interface WorkflowMeedanWorkflow {
  input?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}